#!/usr/bin/env python
# coding: utf-8
#
# xiaoyu <xiaokong1937@gmai.com>
#
# 2014/02/11
#
# Supported Express for weixin app
#
import sys
from operator import itemgetter

reload(sys)

sys.setdefaultencoding('utf-8')

express = {
    'aae': u'AAE快递',
    'anjie': u'安捷快递',
    'anxinda': u'安信达快递',
    'aramex': u'Aramex国际快递',
    'balunzhi': u'巴伦支',
    'baotongda': u'宝通达',
    'benteng': u'成都奔腾国际快递',
    'cces': u'CCES快递',
    'changtong': u'长通物流',
    'chengguang': u'程光快递',
    'chengji': u'城际快递',
    'chengshi100': u'城市100',
    'chuanxi': u'传喜快递',
    'chuanzhi': u'传志快递',
    'chukouyi': u'出口易物流',
    'citylink': u'CityLinkExpress',
    'coe': u'东方快递',
    'cszx': u'城市之星',
    'datian': u'大田物流',
    'dayang': u'大洋物流快递',
    'debang': u'德邦物流',
    'dechuang': u'德创物流',
    'dhl': u'DHL快递',
    'diantong': u'店通快递',
    'dida': u'递达快递',
    'dingdong': u'叮咚快递',
    'disifang': u'递四方速递',
    'dpex': u'DPEX快递',
    'dsu': u'D速快递',
    'ees': u'百福东方物流',
    'ems': u'EMS快递',
    'fanyu': u'凡宇快递',
    'fardar': u'Fardar',
    'fedex': u'国际Fedex',
    'fedexcn': u'Fedex国内',
    'feibang': u'飞邦物流',
    'feibao': u'飞豹快递',
    'feihang': u'原飞航物流',
    'feihu': u'飞狐快递',
    'feite': u'飞特物流',
    'feiyuan': u'飞远物流',
    'fengda': u'丰达快递',
    'fkd': u'飞康达快递',
    'gdyz': u'广东邮政物流',
    'gnxb': u'邮政国内小包',
    'gongsuda': u'共速达物流|快递',
    'guotong': u'国通快递',
    'haihong': u'山东海红快递',
    'haimeng': u'海盟速递',
    'haosheng': u'昊盛物流',
    'hebeijianhua': u'河北建华快递',
    'henglu': u'恒路物流',
    'huacheng': u'华诚物流',
    'huahan': u'华翰物流',
    'huaqi': u'华企快递',
    'huaxialong': u'华夏龙物流',
    'huayu': u'天地华宇物流',
    'huiqiang': u'汇强快递',
    'huitong': u'汇通快递',
    'hwhq': u'海外环球快递',
    'jiaji': u'佳吉快运',
    'jiayi': u'佳怡物流',
    'jiayunmei': u'加运美快递',
    'jinda': u'金大物流',
    'jingdong': u'京东快递',
    'jingguang': u'京广快递',
    'jinyue': u'晋越快递',
    'jixianda': u'急先达物流',
    'jldt': u'嘉里大通物流',
    'kangli': u'康力物流',
    'kcs': u'顺鑫(KCS)快递',
    'kuaijie': u'快捷快递',
    'kuanrong': u'宽容物流',
    'kuayue': u'跨越快递',
    'lejiedi': u'乐捷递快递',
    'lianhaotong': u'联昊通快递',
    'lijisong': u'成都立即送快递',
    'longbang': u'龙邦快递',
    'minbang': u'民邦快递',
    'mingliang': u'明亮物流',
    'minsheng': u'闽盛快递',
    'nell': u'尼尔快递',
    'nengda': u'港中能达快递',
    'ocs': u'OCS快递',
    'pinganda': u'平安达',
    'pingyou': u'中国邮政平邮',
    'pinsu': u'品速心达快递',
    'quanchen': u'全晨快递',
    'quanfeng': u'全峰快递',
    'quanjitong': u'全际通快递',
    'quanritong': u'全日通快递',
    'quanyi': u'全一快递',
    'rpx': u'RPX保时达',
    'rufeng': u'如风达快递',
    'saiaodi': u'赛澳递',
    'santai': u'三态速递',
    'scs': u'伟邦(SCS)快递',
    'shengan': u'圣安物流',
    'shengfeng': u'盛丰物流',
    'shenghui': u'盛辉物流',
    'shentong': u'申通快递（可能存在延迟）',
    'shunfeng': u'顺丰快递',
    'suchengzhaipei': u'速呈宅配',
    'suijia': u'穗佳物流',
    'sure': u'速尔快递',
    'tiantian': u'天天快递',
    'tnt': u'TNT快递',
    'tongcheng': u'通成物流',
    'tonghe': u'通和天下物流',
    'ups': u'UPS快递',
    'usps': u'USPS快递',
    'wanbo': u'万博快递',
    'wanjia': u'万家物流',
    'weitepai': u'微特派',
    'xianglong': u'祥龙运通快递',
    'xinbang': u'新邦物流',
    'xinfeng': u'信丰快递',
    'xingchengzhaipei': u'星程宅配快递',
    'xiyoute': u'希优特快递',
    'yad': u'源安达快递',
    'yafeng': u'亚风快递',
    'yibang': u'一邦快递',
    'yinjie': u'银捷快递',
    'yinsu': u'音素快运',
    'yishunhang': u'亿顺航快递',
    'yousu': u'优速快递',
    'ytfh': u'北京一统飞鸿快递',
    'yuancheng': u'远成物流',
    'yuantong': u'圆通快递',
    'yuanzhi': u'元智捷诚',
    'yuefeng': u'越丰快递',
    'yumeijie': u'誉美捷快递',
    'yunda': u'韵达快递',
    'yuntong': u'运通中港快递',
    'yuxin': u'宇鑫物流',
    'ywfex': u'源伟丰',
    'zengyi': u'增益快递',
    'zhaijisong': u'宅急送快递',
    'zhengzhoujianhua': u'郑州建华快递',
    'zhima': u'芝麻开门快递',
    'zhongtian': u'济南中天万运',
    'zhongtie': u'中铁快运',
    'zhongtong': u'中通快递',
    'zhongxinda': u'忠信达快递',
    'zhongyou': u'中邮物流',
}

pop_express = {
    'debang': u'德邦物流',
    'dhl': u'DHL快递',
    'ems': u'EMS快递',
    'fedex': u'国际Fedex',
    'fedexcn': u'Fedex国内',
    'gnxb': u'邮政国内小包',
    'haihong': u'山东海红快递',
    'huitong': u'汇通快递',
    'jiaji': u'佳吉快运',
    'jingdong': u'京东快递',
    'longbang': u'龙邦快递',
    'shentong': u'申通快递（可能存在延迟）',
    'shunfeng': u'顺丰快递',
    'yuantong': u'圆通快递',
    'yunda': u'韵达快递',
    'zhaijisong': u'宅急送快递',
    'zhongtie': u'中铁快运',
    'zhongtong': u'中通快递',
    'zhongyou': u'中邮物流',
}

def to_table(dict_):


    rt = u'<table class="table">\n'
    for k, v in sorted(dict_.iteritems(), key=itemgetter(0), reverse=False):
        rt += u'\t<tr>\n'
        rt += u'\t\t<td>%s</td>\n\t\t<td>%s</td>\n' % (k, v)
        rt += u'\t</tr>\n'
    rt += u'</table>'
    return rt


if __name__ == '__main__':
    print to_table(express)

